# Generated by Django 4.2.6 on 2023-11-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdata',
            old_name='bim',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='bp',
            new_name='speed',
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='spo2',
            new_name='vibration',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='strick',
        ),
    ]
